name: nitris
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logging: ^1.3.0
  loading_animation_widget: ^1.3.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  provider: ^6.1.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.4.1
  flutter_udid: ^3.0.0
  pinput: ^5.0.0
  otp: ^3.1.3
  local_auth: ^2.3.0
  path: ^1.9.0
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  flutter_staggered_animations: ^1.1.1
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.1.0
  font_awesome_flutter: ^10.8.0
  dropdown_search: ^5.0.6
  share_plus: ^10.1.3
  connectivity_plus: ^5.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/nitris.png
  - assets/images/error/error_illustration.png
  - assets/images/login-main-image.png
  - assets/images/ind.png
  - assets/images/nitris-banner.png
  - assets/images/watermark.png
  - assets/images/mark-nitr.png
  - assets/images/hello-nitr.png